- hosts: web
  become: yes
  tasks:
    - name: "update"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
    - name: "Install lighttpd"
      apt: 
        name: ['lighttpd']
        state: latest
      
    - name: "create www directory for lighttpd"
      file:
        path: /var/www/website
        state: directory
        mode: '0775'
        owner: "www-data"
        group: "www-data"

    - name: "copy files file to correct path"
      copy:
        src: ../../website/
        dest: /var/www/website #This gets the * file from build/ directory and copies it to /var/www/html



